Added TaskService interface and updated TaskController to use it
artlyt/spring pull request #1
Opened 2024-08-17 15:30 UTC by artlyt

2024-08-17 15:32 UTC, artlyt commented
![image](https://github.com/user-attachments/assets/1c2d4339-5995-4991-8d07-8ddae46d7557)

2024-08-18 13:08 UTC, greslayer requested changes

2024-08-18 13:08 UTC, greslayer commented on src/main/java/com/example/todo/service/TaskServiceImpl.java
> +    @Autowired
добавить ломбок и использовать его для генерации конструктора

2024-08-20 19:53 UTC, artlyt commented on src/main/java/com/example/todo/service/TaskServiceImpl.java
> +    @Autowired
Dear Arkadii @greslayer, lombock is now added and used to generate TaskServiceImpl constructor

2024-08-20 19:53 UTC, merged